# 开发环境配置文件

server:
  port: 8081     # Springboot占用端口

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver     # 数据库驱动
      url: /MysqlUrl/    # 数据库链接
      username: /confidential/     # 数据库账号
      password: /confidential/     # 数据库密码
  devtools:
    restart:
      enabled: true     # 开启热更新